spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dms?autoReconnect=true&useSSL=false&useUnicode-true&characterEncoding=utf8
    username: dms
    password: dms
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create # none, create, update, validate
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  sql:
    init:
      mode: never # never,

locale: en